### ISSUE TITLE
Trustability grid

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/surfclass#48]
Predict_prob

**Comment by NicolaiLolansen** [comment]
```
predict_proba(self, X)
```

Returns vector of length (n=num_classes) with "probability" (normalized number of trees) for each class for each observation

**Comment by NicolaiLolansen** [comment]
fixed in #50 

surfclass classify can now be called with a --prob argument with an output path. Will output an additional raster with the highest probability (float32 between 0 and 1) for the class chosen.
